SELECT * FROM CALENDAR;

--DROP TABLE CALENDAR CASCADE CONSTRAINTS;
--DROP SEQUENCE SEQ_CAL;

--일정관리 테이블 생성
CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL
);

--시퀀스 생성
CREATE SEQUENCE SEQ_CAL START WITH 1 INCREMENT BY 1;

--외래 키 제약조건 생성
ALTER TABLE CALENDAR ADD CONSTRAINT FK_CAL_ID 
FOREIGN KEY(ID) REFERENCES MEMBER(ID);

--날짜별로 숫자를 매겨줌
SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE 
FROM (SELECT ROW_NUMBER() OVER( PARTITION BY SUBSTR(RDATE, 1, 8) ORDER BY RDATE ASC )	RNUM,
	SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM CALENDAR
WHERE ID='1' AND SUBSTR(RDATE, 1, 6)='7') --201907처럼 6글자 따오기
WHERE RNUM BETWEEN 1 AND 5 ;