--DROP TABLE VOTER CASCADE CONSTRAINTS;
--DROP SEQUENCE SEQ_VOTER;

CREATE TABLE VOTER(
    VOTERID NUMBER(10) NOT NULL,
    POLLID NUMBER(10) NOT NULL,
    POLLSUBID NUMBER(10) NOT NULL,
    ID VARCHAR2(1000) ,
    REGDATE DATE ,
    CONSTRAINT VOTER_PK PRIMARY KEY(VOTERID)
);

CREATE SEQUENCE SEQ_VOTER START WITH 1 INCREMENT BY 1;

--외래키
ALTER TABLE VOTER ADD CONSTRAINT VOTER_FK FOREIGN KEY(POLLID) REFERENCES POLL(POLLID);
ALTER TABLE VOTER ADD CONSTRAINT VOTER_FK2 FOREIGN KEY(POLLSUBID) REFERENCES POLLSUB(POLLSUBID);
ALTER TABLE VOTER ADD CONSTRAINT VOTER_FK3 FOREIGN KEY(ID) REFERENCES MEMBER(ID);