SELECT * FROM COFFEE_MEM order by REG_DATE;
--drop table coffee_mem;

CREATE TABLE COFFEE_MEM (
	ID VARCHAR2(20) NOT NULL,
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	AGE NUMBER(2) NOT NULL ,
	REG_DATE DATE,
	AUTH NUMBER(1) NOT NULL --관리자:1, 일반:3
);


INSERT INTO COFFEE_MEM VALUES('1', '1', 'ADMIN', 29, SYSDATE, 1);
INSERT INTO COFFEE_MEM VALUES('jamjam', '1', 'James', 55, SYSDATE, 3);
INSERT INTO COFFEE_MEM VALUES('mc', '1', 'McDonald', 89, SYSDATE, 3);