SELECT * FROM COFFEE_MENU;
--DROP TABLE COFFEE_MENU;

CREATE TABLE COFFEE_MENU(
	SEQ NUMBER(8) PRIMARY KEY,	
	NAME VARCHAR(30) NOT NULL,
	PRICE_SHORT NUMBER(10) ,
	PRICE_TALL NUMBER(10) NOT NULL,
	PRICE_GRANDE NUMBER(10)
);

CREATE SEQUENCE SEQ_COF_MENU START WITH 1 INCREMENT BY 1;


INSERT INTO COFFEE_MENU VALUES(SEQ_COF_MENU.NEXTVAL ,'오늘의 커피', 2500, 3000, 3500);