SELECT * FROM COFFEE_ORDER;
--DROP TABLE ORDER_LOG;

SELECT * FROM user_objects;



--CREATE SEQUENCE SEQ_COF_ORDER START WITH 1 INCREMENT BY 1;

CREATE TABLE COFFEE_ORDER 
(
  ORDER_NUM NUMBER(10, 0) NOT NULL 
, CUSTOMER VARCHAR2(20 BYTE) NOT NULL 
, MENU_NAME VARCHAR2(20 BYTE) 
, SIZE_STG VARCHAR2(20 BYTE) 
, SYRUP VARCHAR2(20 BYTE) 
, ADD_SHOT VARCHAR2(20 BYTE) 
, ADD_WHIP VARCHAR2(20 BYTE) 
, AMOUNT NUMBER(10, 0) 
, PRICE NUMBER(10, 0) 
, ORD_DATE DATE 
, CONSTRAINT COFFEE_ORDER_PK PRIMARY KEY   (    ORDER_NUM   )
  USING INDEX   (
  	CREATE UNIQUE INDEX COFFEE_ORDER_PK ON COFFEE_ORDER (ORDER_NUM ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;