SELECT * FROM CALENDAR;

--DROP TABLE CALENDAR CASCADE CONSTRAINTS;
--DROP SEQUENCE SEQ_CAL;

--일정관리 테이블 생성
CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL
);

--시퀀스 생성
CREATE SEQUENCE SEQ_CAL START WITH 1 INCREMENT BY 1;

--외래 키 제약조건 생성
ALTER TABLE CALENDAR ADD CONSTRAINT FK_CAL_ID 
FOREIGN KEY(ID) REFERENCES MEMBER(ID);