CREATE TABLE BBS (
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

SELECT SEQ_BBS.CURRVAL FROM DUAL;
SELECT SEQ_BBS.NEXTVAL FROM DUAL;
DROP SEQUENCE SEQ_BBS;
DELETE FROM BBS WHERE SEQ = 4;

SELECT * FROM BBS ORDER BY SEQ;

ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

UPDATE BBS SET CONTENT = '1열' || CHR(13)||CHR(10) || '2열') WHERE SEQ = 1;
SELECT * FROM BBS;
SELECT * FROM MEMBER;
INSERT INTO BBS VALUES(
	SEQ_BBS.NEXTVAL,
	'system',
	'bbs test2',
	'대충 게시판 내용',
	SYSDATE,
	1,
	1
);

