--DROP 준비
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
	ID VARCHAR2(20) PRIMARY KEY,
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE,
	AUTH NUMBER(1) NOT NULL
);

SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES('system', 'system', 'admin', 'dd@dd.com', 1);
INSERT INTO MEMBER VALUES('1', '1', 'ad', '313@133.com', 1);
INSERT INTO MEMBER VALUES('minhj', '1234', 'minhj', '33@33.com', 3);
ROLLBACK;