-- CONN TO HR 
-- FIRST_NAME이 Julia인 사원의 정보
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'Julia';
-- 급여가 9000 이상인 사원의 정보
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 9000;
-- 이름이 Shanta 보다 큰 이름? (가나다 순 조건; char)
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME >= '1';
-- manager id가 없는 사람
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE MANAGER_ID IS NULL AND FIRST_NAME = 'Steven';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'John' AND SALARY >= 5000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE HIRE_DATE >= '08/01/01';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE HIRE_DATE >= TO_DATE('080101', 'YYMMDD');
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE HIRE_DATE >= TO_MONTH('0801', 'YYMM');

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME=ANY('Julia', 'John', 'Steven');
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY = ANY(8000,3200);
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY NOT IN (8000,3200);
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME IN('Julia', 'John');
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME NOT IN('Julia', 'John');
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES e WHERE EXISTS (SELECT 1 FROM DUAL WHERE e.job_id = 'IT_PROG' );

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 8000 AND 9000;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 8000 AND SALARY <= 9000;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY NOT BETWEEN 8000 AND 9000;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < 8000 OR SALARY > 9000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME LIKE 'G_ra_d';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE FIRST_NAME LIKE 'K%y';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY LIKE '9%';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY LIKE '%9%';
SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '06/01%';